server:
  port: 8761

eureka:
  shouldUseDns: false
  numberRegistrySyncRetries: 1
  instance:
    preferIpAddress: true
#    hostname: service-registry
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}
#  server:
#    enable-self-preservation: false
